name: Backend Tests

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
      - 'shared/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    branches: [ main, dev ]
    paths:
      - 'backend/**'
      - 'shared/**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      working-directory: ./backend
      run: |
        uv pip install --system -r requirements.txt
        uv pip install --system -r requirements-dev.txt

    - name: Create .env file
      run: |
        echo "PATH_PROJECT_HOME=${{ github.workspace }}" > .env
        echo "CLAUDE_API_KEY=test_api_key" >> .env
        echo "JWT_SECRET_KEY=test_secret_key" >> .env

    - name: Run tests with pytest
      working-directory: ./backend
      env:
        PATH_PROJECT_HOME: ${{ github.workspace }}
        CLAUDE_API_KEY: test_api_key
        JWT_SECRET_KEY: test_secret_key
        JWT_ALGORITHM: HS256
        JWT_EXPIRE_MINUTES: 1440
      run: |
        pytest tests/ -v --cov=app --cov-report=xml --cov-report=term

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./backend/coverage.xml
        flags: backend
        name: backend-coverage
        fail_ci_if_error: false
